### ISSUE TITLE
Option to select audio driver

### ISSUE THREAD

**Issue by Lignum** [incinirate/Riko4#2]
When starting riko, this happens for me:
```
Audio driver 0: pulseaudio
Audio driver 1: alsa
Audio driver 2: dsp
Audio driver 3: disk
Audio driver 4: dummy
Assertion 'p' failed at pulsecore/memblock.c:952, function pa_mempool_block_size_max(). Aborting.
[1]    7598 abort (core dumped)  ./riko4
```
While that should probably be fixed, pulseaudio loves breaking, so perhaps there should be an option to select a different audio driver instead.

**Comment by incinirate** [comment]
Do you have any suggestions for how one would select a different driver? Maybe a config file? Command line option?

**Comment by incinirate** [comment]
Perhaps even a Lua interface to switch audio drivers in-game?

**Comment by CrazedProgrammer** [comment]
Should probably be an optional config file option, I think most users don't want to deal with this.

**Comment by Lignum** [comment]
Yeah, or an environment variable.

**Comment by incinirate** [comment]
By the way, temporary fix to this issue run Riko4 with command line option `--noaud`
Audio will be disabled, but Riko4 will actually run.

**Comment by incinirate** [comment]
By the way @Lignum if you do not already have these packages installed can you try running Riko4 with `libasound2-dev` and `libpulse-dev` installed?

**Comment by incinirate** [comment]
After further investigation, it appears that I'm not actually supposed to (or are currently) changing or setting the graphics driver, SDL does that by itself; however, you can override it with the `SDL_AUDIODRIVER` environment variable.

As to the reason it crashes: I'm assuming that the settings I pass to SDL for what I want to happen are how it is, turns out that these settings can be modified, and I'm not handling that. In this exact case, the sample size is being reduced, so Riko tries to write too much sound data to a smaller buffer than it's expecting, it's not a hard fix so I should push a fix either tonight or tomorrow.
